# Generated by Django 4.0.1 on 2022-01-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footistix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
