# Generated by Django 4.0.1 on 2022-01-25 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footistix', '0002_alter_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
