# Generated by Django 4.0.1 on 2022-02-01 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footistix', '0005_alter_playervalues_player_playerdefaults'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
