# Generated by Django 4.0.1 on 2022-02-07 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('footistix', '0006_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='NationalTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('league', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='league',
        ),
        migrations.AddField(
            model_name='player',
            name='national_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='footistix.nationalteam'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='footistix.team'),
        ),
    ]
