# Generated by Django 4.0.1 on 2022-02-07 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footistix', '0007_nationalteam_team_remove_player_league_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RatingSkils',
            new_name='RatingSkill',
        ),
    ]
