# Generated by Django 4.0.1 on 2022-02-01 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('footistix', '0004_alter_rating_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playervalues',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='footistix.player'),
        ),
        migrations.CreateModel(
            name='PlayerDefaults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='footistix.player')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='footistix.skill')),
            ],
        ),
    ]
