# Generated by Django 4.0.1 on 2022-04-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footistix', '0008_rename_ratingskils_ratingskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tier', models.CharField(max_length=255)),
            ],
        ),
    ]
